In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import os
import glob

# Import Dataset

In [3]:
os.getcwd()

'C:\\Users\\ill will\\Desktop\\Code\\springboard\\Capstone_1\\notebooks'

In [4]:
import importlib.util
import sys

current_file_path = os.path.abspath(os.path.join("__file__" ,"../.."))
current_file_path

'C:\\Users\\ill will\\Desktop\\Code\\springboard\\Capstone_1'

In [5]:
import_eda_path = os.path.join(current_file_path,'src','tools')
sys.path.append(os.path.abspath(os.path.join(import_eda_path)))
import eda_tools as eda

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

# H2O Random Forests

In [6]:
import h2o

In [7]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode)

c:\users\illwil~1\virtua~1\capsto~1\lib\site-packages\h2o\backend\server.py:258: UserWarning:   You have a 32-bit version of Java. H2O works best with 64-bit Java.
  Please download the latest 64-bit Java SE JDK from Oracle.

  warn("  You have a 32-bit version of Java. H2O works best with 64-bit Java.\n"

  Starting server from c:\users\illwil~1\virtua~1\capsto~1\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\ILLWIL~1\AppData\Local\Temp\tmpphnuy8rl
  JVM stdout: C:\Users\ILLWIL~1\AppData\Local\Temp\tmpphnuy8rl\h2o_ill_will_started_from_python.out
  JVM stderr: C:\Users\ILLWIL~1\AppData\Local\Temp\tmpphnuy8rl\h2o_ill_will_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.

--------------------------  -------------------------------
H2O cluster uptime:         04 secs
H2O cluster timezone:       America/Denver
H2O data parsing timezone:  UTC
H2O cluster version:        3.18.0.9
H2O cluster version age:    5 days
H2O cluster name:           H2O_from_python_ill_will_mjoph7
H2O cluster total nodes:    1
H2O cluster free memory:    247.5 Mb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Algos, AutoML, Core V3, Core V4
Python version:             3.6.1 final
--------------------------  -------------------------------

In [8]:
df = h2o.import_file('mega_features.csv')

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [9]:
df.col_names

['movie_id',
 'title',
 'budget',
 'revenue',
 'runtime',
 'release_month',
 'release_year',
 'release_dow',
 'actor_gender',
 'actor_credits',
 'actor_net_to_date',
 'producer_gender',
 'producer_credits',
 'producer_net_to_date',
 'writer_gender',
 'writer_credits',
 'writer_net_to_date',
 'director_gender',
 'director_credits',
 'director_net_to_date',
 'genre_count',
 'language_count',
 'net',
 'target']

In [10]:
x = df.col_names
x.remove('revenue')
x.remove('movie_id')
x.remove('net')
x.remove('target')
y='target'

In [11]:
x

['title',
 'budget',
 'runtime',
 'release_month',
 'release_year',
 'release_dow',
 'actor_gender',
 'actor_credits',
 'actor_net_to_date',
 'producer_gender',
 'producer_credits',
 'producer_net_to_date',
 'writer_gender',
 'writer_credits',
 'writer_net_to_date',
 'director_gender',
 'director_credits',
 'director_net_to_date',
 'genre_count',
 'language_count']

In [12]:
df['target'] = df['target'].asfactor()
df['release_month'] = df['release_month'].asfactor()
df['release_year'] = df['release_year'].asfactor()
df['release_dow'] = df['release_dow'].asfactor()
for col in x:
    if 'gender' in col:
        df[col] = df[col].asfactor()

In [13]:
df.summary()

,movie_id,title,budget,revenue,runtime,release_month,release_year,release_dow,actor_gender,actor_credits,actor_net_to_date,producer_gender,producer_credits,producer_net_to_date,writer_gender,writer_credits,writer_net_to_date,director_gender,director_credits,director_net_to_date,genre_count,language_count,net,target
type,int,string,int,int,int,enum,enum,enum,enum,int,int,enum,int,int,enum,int,int,enum,int,int,int,int,int,enum
mins,5.0,NaN,7000.0,527.0,41.0,,,,,0.0,-46587843.0,,0.0,-49184462.0,,0.0,-45549103.0,,0.0,-71596603.0,1.0,1.0,-71626175.0,
mean,74716.81344902386,NaN,29182540.72993492,82983712.30477223,106.35249457700651,,,,,3.5878524945770067,312203477.3308026,,2.7375271149674623,228477069.95119306,,0.2885032537960954,17370403.785249457,,1.8134490238611713,156684330.63015184,2.5260303687635575,1.4229934924078091,53801171.57483731,
maxs,407887.0,NaN,280000000.0,2787965087.0,238.0,,,,,28.0,5561359969.0,,34.0,6334752999.0,,5.0,1507372773.0,,25.0,7311069227.0,6.0,8.0,2550965087.0,
sigma,93646.69785899286,NaN,36316858.78126402,170696481.187295,18.443988609072292,,,,,5.695626067015391,696881968.6474175,,4.918497687558805,569284607.6251774,,0.6747003472811639,88824197.15997343,,3.159858370378549,541655225.8825799,1.0584827561207955,0.8446244004335702,146782847.56091154,
zeros,0,0,0,0,0,,,,,399,399,,437,437,,736,736,,441,441,0,0,0,
missing,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,19995.0,Avatar,237000000.0,2787965087.0,162.0,12,2009,3,2,0.0,0.0,2,3.0,2328916599.0,2,1.0,420000000.0,2,6.0,2585704352.0,4.0,2.0,2550965087.0,1
1,99861.0,Avengers: Age of Ultron,280000000.0,1405403694.0,141.0,4,2015,2,2,11.0,3940617206.0,2,8.0,4891494230.0,2,1.0,-130536.0,2,2.0,1299427374.0,3.0,1.0,1125403694.0,1
2,41154.0,Men in Black 3,225000000.0,624026776.0,106.0,5,2012,2,2,12.0,3150078356.0,2,4.0,957515311.0,0,0.0,0.0,2,6.0,1068161961.0,3.0,1.0,399026776.0,1
3,122917.0,The Hobbit: The Battle of the Five Armies,250000000.0,956019788.0,144.0,12,2014,2,2,2.0,762878416.0,2,5.0,2031848765.0,2,0.0,0.0,2,8.0,4499623032.0,3.0,1.0,706019788.0,1
4,37724.0,Skyfall,200000000.0,1108561013.0,143.0,10,2012,3,2,6.0,955438019.0,1,6.0,1871145305.0,2,2.0,77012923.0,2,5.0,505313187.0,3.0,1.0,908561013.0,1
5,534.0,Terminator Salvation,200000000.0,371353001.0,115.0,5,2009,2,2,8.0,1043812724.0,2,0.0,0.0,2,1.0,59423648.0,2,3.0,289826697.0,3.0,2.0,171353001.0,1
6,168259.0,Furious 7,190000000.0,1506249360.0,137.0,4,2015,2,2,9.0,866986795.0,2,3.0,706317639.0,2,0.0,0.0,2,4.0,500195419.0,1.0,1.0,1316249360.0,1
7,14161.0,2012,200000000.0,769653595.0,158.0,10,2009,5,2,11.0,160061851.0,2,8.0,751824274.0,2,0.0,0.0,2,3.0,1266536012.0,3.0,8.0,569653595.0,1
8,76757.0,Jupiter Ascending,176000003.0,183987723.0,124.0,2,2015,2,1,0.0,0.0,2,1.0,46126565.0,1,2.0,374463149.0,1,5.0,1240562378.0,4.0,1.0,7987720.0,1
9,246655.0,X-Men: Apocalypse,178000000.0,543934787.0,144.0,5,2016,2,2,5.0,254526261.0,1,6.0,1585962509.0,2,0.0,0.0,2,7.0,1283300214.0,1.0,1.0,365934787.0,1

In [14]:
train, valid, test = df.split_frame(ratios=[0.7, 0.2])
print(df.shape)
print(train.shape)
print(valid.shape)
print(test.shape)

(922, 24)
(639, 24)
(199, 24)
(84, 24)

In [15]:
from h2o.estimators.random_forest import H2ORandomForestEstimator
drf = H2ORandomForestEstimator(nfolds=3,ntrees=200,
    max_depth=30,
    stopping_rounds=2,
    stopping_tolerance=0.01,
    score_each_iteration=True)
drf.train(x=x, y=y, training_frame=train, validation_frame=valid)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [16]:
drf.model_performance(test_data=test)

ModelMetricsBinomial: drf
** Reported on test data. **

MSE: 0.23246696554084118
RMSE: 0.4821482816943779
LogLoss: 1.4130131471699388
Mean Per-Class Error: 0.3276470588235294
AUC: 0.671470588235294
Gini: 0.3429411764705881
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.4117647058823529:

       0    1    Error    Rate
-----  ---  ---  -------  -----------
0      8    26   0.7647   (26.0/34.0)
1      2    48   0.04     (2.0/50.0)
Total  10   74   0.3333   (28.0/84.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.411765     0.774194  17
max f2                       0.323529     0.88968   20
max f0point5                 0.764706     0.732323  7
max accuracy                 0.411765     0.666667  17
max precision                0.882353     0.818182  3
max recall                   0.323529     1         20
max specificity              1            0.941176  0
max absolute_mcc             0.764706     0.340819  7
max min_per_class_accuracy   0.705882     0.617647  8
max mean_per_class_accuracy  0.764706     0.672353  7

Gains/Lift Table: Avg response rate: 59.52 %

    group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    cumulative_response_rate    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  --------  -----------------  ---------------  --------------------------  --------------  -------------------------  --------  -----------------
    1        0.0952381                   1                  1.26      1.26               0.75             0.75                        0.12            0.12                       26        26
    2        0.119048                    0.941176           1.68      1.344              1                0.8                         0.04            0.16                       68        34.4
    3        0.261905                    0.882353           1.4       1.37455            0.833333         0.818182                    0.2             0.36                       40        37.4545
    4        0.369048                    0.823529           1.30667   1.35484            0.777778         0.806452                    0.14            0.5                        30.6667   35.4839
    5        0.404762                    0.792157           0.56      1.28471            0.333333         0.764706                    0.02            0.52                       -44       28.4706
    6        0.52381                     0.705882           0.84      1.18364            0.5              0.704545                    0.1             0.62                       -16       18.3636
    7        0.678571                    0.647059           0.775385  1.09053            0.461538         0.649123                    0.12            0.74                       -22.4615  9.05263
    8        0.714286                    0.588235           0.56      1.064              0.333333         0.633333                    0.02            0.76                       -44       6.4
    9        0.797619                    0.488235           1.2       1.07821            0.714286         0.641791                    0.1             0.86                       20        7.8209
    10       0.892857                    0.361765           1.05      1.0752             0.625            0.64                        0.1             0.96                       5         7.52
    11       1                           0.264706           0.373333  1                  0.222222         0.595238                    0.04            1                          -62.6667  0

In [17]:
drf.score_history()

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_lift,training_classification_error,validation_rmse,validation_logloss,validation_auc,validation_lift,validation_classification_error
0,,2018-05-16 22:48:37,2.492 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2018-05-16 22:48:37,2.531 sec,1.0,0.579713,11.562577,0.618915,1.136915,0.311024,0.652594,14.589631,0.538216,1.040338,0.386935
2,,2018-05-16 22:48:37,2.573 sec,2.0,0.588303,11.144514,0.590746,1.106891,0.318066,0.581933,8.440388,0.534277,1.041158,0.386935
3,,2018-05-16 22:48:37,2.620 sec,3.0,0.591952,10.586641,0.564555,1.069743,0.329243,0.546070,5.293821,0.547105,1.040152,0.371859
4,,2018-05-16 22:48:37,2.656 sec,4.0,0.577327,9.515932,0.573550,1.080282,0.324074,0.525739,3.315759,0.580849,1.151398,0.366834
5,,2018-05-16 22:48:37,2.691 sec,5.0,0.563523,8.398853,0.584663,1.080761,0.328696,0.525206,2.675449,0.559666,1.165105,0.361809
6,,2018-05-16 22:48:37,2.728 sec,6.0,0.558680,7.740343,0.581231,1.085957,0.327787,0.518544,2.185792,0.567330,1.124929,0.381910
7,,2018-05-16 22:48:37,2.795 sec,7.0,0.545851,6.786493,0.585501,1.101625,0.329527,0.513542,1.539637,0.579945,1.242779,0.381910
8,,2018-05-16 22:48:38,2.849 sec,8.0,0.541785,6.109370,0.579281,1.098925,0.328479,0.510510,1.367577,0.578454,1.287748,0.381910
9,,2018-05-16 22:48:38,2.900 sec,9.0,0.531751,5.654030,0.586560,1.093259,0.328549,0.511586,1.213708,0.567756,1.325307,0.381910
10,,2018-05-16 22:48:38,2.944 sec,10.0,0.519927,4.724708,0.595539,1.116279,0.327532,0.511829,1.051802,0.570950,1.413661,0.381910
11,,2018-05-16 22:48:38,2.983 sec,11.0,0.512897,4.333228,0.601686,1.120025,0.327044,0.510138,1.048137,0.572600,1.413661,0.381910
12,,2018-05-16 22:48:38,3.025 sec,12.0,0.510869,3.878326,0.594048,1.108510,0.327044,0.506639,0.880986,0.581541,1.505675,0.381910
13,,2018-05-16 22:48:38,3.061 sec,13.0,0.507133,3.514850,0.592181,1.106091,0.326531,0.504104,0.873834,0.585374,1.449909,0.386935
14,,2018-05-16 22:48:38,3.100 sec,14.0,0.501785,3.199018,0.598194,1.107612,0.326019,0.504698,0.874078,0.584416,1.449909,0.376884
15,,2018-05-16 22:48:38,3.149 sec,15.0,0.500308,3.046478,0.598765,1.114535,0.326019,0.503552,0.870755,0.592932,1.449909,0.376884
16,,2018-05-16 22:48:38,3.188 sec,16.0,0.494909,2.683111,0.609218,1.140698,0.326019,0.504670,0.873903,0.590803,1.427254,0.376884
17,,2018-05-16 22:48:38,3.245 sec,17.0,0.492722,2.477678,0.608475,1.144806,0.321317,0.507407,0.724629,0.576964,1.631148,0.376884

In [18]:
drf.predict(test)

drf prediction progress: |████████████████████████████████████████████████| 100%

predict,p0,p1
1,0,1
1,0.117647,0.882353
1,0.117647,0.882353
1,0.117647,0.882353
1,0.176471,0.823529
1,0,1
1,0,1
1,0.588235,0.411765
1,0.117647,0.882353
1,0.294118,0.705882

In [19]:
test

movie_id,title,budget,revenue,runtime,release_month,release_year,release_dow,actor_gender,actor_credits,actor_net_to_date,producer_gender,producer_credits,producer_net_to_date,writer_gender,writer_credits,writer_net_to_date,director_gender,director_credits,director_net_to_date,genre_count,language_count,net,target
119450,Dawn of the Planet of the Apes,1.7e+08,7.10645e+08,130,6,2014,3,2,1,-3.49504e+06,2,1,3.8986e+08,0,2,1.24109e+08,2,3,1.47566e+08,4,1,5.40645e+08,1
76341,Mad Max: Fury Road,1.5e+08,3.78858e+08,120,5,2015,2,2,3,-4.65878e+07,2,4,5.08009e+08,2,2,3.04742e+08,2,6,4.29999e+08,4,1,2.28858e+08,1
98566,Teenage Mutant Ninja Turtles,1.25e+08,4.772e+08,101,8,2014,3,1,1,1.55561e+07,2,8,5.62808e+08,0,0,0,0,4,3.58274e+08,5,1,3.522e+08,1
157353,Transcendence,1e+08,1.03039e+08,119,4,2014,2,2,23,3.53201e+09,2,3,1.98304e+08,0,0,0,2,0,0,4,1,3.03926e+06,1
11678,Vertical Limit,7.5e+07,2.15664e+08,124,12,2000,4,2,0,0,2,0,0,2,0,0,2,2,4.49483e+08,3,2,1.40664e+08,1
188207,The Legend of Hercules,7e+07,6.12795e+07,99,1,2014,4,2,0,0,2,0,0,2,0,0,2,14,2.88921e+08,2,1,-8.72055e+06,0
11170,We Are Marshall,6.5e+07,4.35454e+07,124,12,2006,1,2,6,2.30237e+08,2,0,0,0,0,0,2,2,3.11281e+08,1,1,-2.14546e+07,0
16866,Planet 51,7e+07,1.04946e+08,91,11,2009,3,2,8,2.75501e+08,2,0,0,2,0,0,2,0,0,5,2,3.49458e+07,1
14411,Sinbad: Legend of the Seven Seas,6e+07,2.62883e+07,86,7,2003,2,2,7,7.93413e+08,2,2,4.66973e+08,2,0,0,2,0,0,3,3,-3.37117e+07,0
8413,Event Horizon,6e+07,2.66732e+07,96,8,1997,4,2,2,4.31973e+07,0,0,0,2,0,0,2,1,1.04196e+08,3,2,-3.33268e+07,0

In [20]:
drf.gains_lift().as_data_frame()

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,cumulative_response_rate,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.211268,1.000000,1.144806,1.144806,0.770370,0.770370,0.241860,0.241860,14.480620,14.480620
1,,2,0.350548,0.833333,1.035223,1.101267,0.696629,0.741071,0.144186,0.386047,3.522341,10.126661
2,,3,0.419405,0.800000,1.080761,1.097900,0.727273,0.738806,0.074419,0.460465,8.076110,9.790003
3,,4,0.510172,0.750000,1.076103,1.094022,0.724138,0.736196,0.097674,0.558140,7.610265,9.402197
4,,5,0.632238,0.666667,1.162165,1.107178,0.782051,0.745050,0.141860,0.700000,16.216458,10.717822
5,,6,0.702660,0.571429,0.891628,1.085575,0.600000,0.730512,0.062791,0.762791,-10.837209,8.557518
6,,7,0.801252,0.444444,0.825581,1.053584,0.555556,0.708984,0.081395,0.844186,-17.441860,5.358376
7,,8,0.901408,0.312500,0.743023,1.019077,0.500000,0.685764,0.074419,0.918605,-25.697674,1.907703
8,,9,1.000000,0.000000,0.825581,1.000000,0.555556,0.672926,0.081395,1.000000,-17.441860,0.000000

In [21]:
drf._model_json['output']['variable_importances'].as_data_frame()

                variable  relative_importance  scaled_importance  percentage
0           release_year           367.662140           1.000000    0.239916
1          release_month           222.019302           0.603868    0.144877
2                runtime           126.641617           0.344451    0.082639
3   producer_net_to_date           106.812096           0.290517    0.069700
4                 budget            88.596191           0.240972    0.057813
5            release_dow            88.309158           0.240191    0.057626
6      actor_net_to_date            58.922047           0.160261    0.038449
7          actor_credits            58.124401           0.158092    0.037929
8   director_net_to_date            57.143963           0.155425    0.037289
9            genre_count            57.091576           0.155283    0.037255
10      director_credits            45.512489           0.123789    0.029699
11      producer_credits            43.090649           0.117202    0.028119
12       producer_gender            40.996841           0.111507    0.026752
13          actor_gender            40.118832           0.109119    0.026179
14        language_count            34.863693           0.094825    0.022750
15         writer_gender            33.608025           0.091410    0.021931
16       director_gender            32.966072           0.089664    0.021512
17    writer_net_to_date            18.422533           0.050107    0.012022
18        writer_credits            11.562086           0.031448    0.007545

In [24]:
from h2o.grid.grid_search import H2OGridSearch

m = H2ORandomForestEstimator(nfolds=3)

hyper_parameters = {
    'ntrees':[10,50,100,200,500],
    'max_depth':[5,10,15,20,25],   
}

drf_grid_search = H2OGridSearch(m, hyper_parameters, search_criteria)

NameError: name 'search_criteria' is not defined

In [23]:
drf_grid_search.train(x=x,y=y, training_frame=train, validation_frame=valid)

drf Grid Build progress: |████████████████████████████████████████████████| 100%

H2OServerError: HTTP 500 Server Error:
'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>\n<title>Error 500 Server Error</title>\n</head>\n<body>\n<h2>HTTP ERROR: 500</h2>\n<p>Problem accessing /99/Grids/Grid_DRF_py_11_sid_ae5b_model_python_1526532504109_156. Reason:\n<pre>    Server Error</pre></p>\n<hr /><i><small>Powered by Jetty://</small></i>\n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n</body>\n</html>\n'

In [ ]:
print(drf_grid_search.sort_by('F1', False))

In [ ]:
drf_grid_search.show()